/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetTvRageID.java
 *
 * Created on 21 Φεβ 2010, 12:18:09 μμ
 */
package tools.internetUpdate.tvrage;

import database.DBHelper;
import database.SeriesRecord;
import java.awt.Dialog.ModalityType;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import myComponents.MyMessages;
import myComponents.MyUsefulFunctions;
import myComponents.myGUI.MyDraggable;
import myseries.MySeries;
import myseries.series.AdminSeries;
import myseries.series.Series;
import tools.internetUpdate.InternetUpdate;
import tools.internetUpdate.tvrage.SearchTvRage.TvRageSeries;

/**
 * Get TvRage id form
 * @author lordovol
 */
public class TrGetId extends MyDraggable {

  private MySeries myS;
  private int series_ID = 0;
  private AdminSeries adminSeries;
  String title;
  ComboBoxModel resultsModel = new DefaultComboBoxModel();
  public int tvRageID = 0;
  private boolean isConected;
  private static final long serialVersionUID = 345645747547L;

  {
    isConected = MyUsefulFunctions.hasInternetConnection(InternetUpdate.TV_RAGE_URL);
  }

  /** Creates new form GetTvRageID */
  public TrGetId() {
  }

  /**
   * Creates a tvrage get id from My series form
   * @param myS MySeries form
   * @param series_ID The series ID
   * @param title The series title
   */
  public TrGetId(MySeries myS, int series_ID, String title) {
    this.myS = myS;
    this.series_ID = series_ID;
    this.title = title;
    getID();

  }

  /**
   * Creates a TvRage get id from admin series form
   * @param adminSeries The ad
   * @param title
   */
  public TrGetId(AdminSeries adminSeries, String title) {
    this.adminSeries = adminSeries;
    this.title = title;
    getID();
    adminSeries.setModalityType(ModalityType.APPLICATION_MODAL);
  }

  private void getID() {
    if (!isConected) {
      MySeries.logger.log(Level.WARNING, "Could not connect to internet");
      MyMessages.internetError();
      button_cancelActionPerformed(null);
      return;
    }
    initComponents();
    label_title.setText("Select the right series from the results found for " + title);
    setLocationRelativeTo(null);
    setLocation(getX(), 200);
    setModalityType(ModalityType.MODELESS);
    pack();
    setVisible(true);
    MySeries.logger.log(Level.INFO, "Searching for series " + title);
    SearchTvRage s = new SearchTvRage(title, this);
    Thread t = new Thread(s);
    t.start();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    label_title = new javax.swing.JLabel();
    button_ok = new javax.swing.JButton();
    button_cancel = new javax.swing.JButton();
    progress = new javax.swing.JProgressBar();
    combo_results = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Internet Update");

    label_title.setText("jLabel2");

    button_ok.setText("OK");
    button_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_okActionPerformed(evt);
      }
    });

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    progress.setString("");
    progress.setStringPainted(true);

    combo_results.setModel(resultsModel);

    jLabel2.setText("Results");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(button_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button_cancel)
                .addGap(18, 18, 18)
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(10, 10, 10))
              .addComponent(combo_results, 0, 323, Short.MAX_VALUE))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label_title)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(combo_results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(button_ok)
            .addComponent(button_cancel))
          .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
    dispose();
    //MySeries.glassPane.deactivate();
    if (adminSeries != null) {
      adminSeries.setModalityType(ModalityType.APPLICATION_MODAL);
      if (tvRageID > 0) {
        adminSeries.textfield_tvRageID.setText(String.valueOf(tvRageID));
      }
      adminSeries.setVisible(true);
    } else {
      InternetUpdate iu = new InternetUpdate(myS, Series.getCurrentSerial());
    }

  }//GEN-LAST:event_button_cancelActionPerformed

  private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
    TvRageSeries sel = (TvRageSeries) combo_results.getSelectedItem();
    tvRageID = Integer.parseInt(sel.id);
    if (series_ID > 0) {
      try {
        SeriesRecord cSeries = DBHelper.getSeriesByID(series_ID);
        cSeries.setTvrage_ID(tvRageID);
        cSeries.save();
        Series.getCurrentSerial().setTvrage_ID(tvRageID);
      } catch (SQLException ex) {
        MySeries.logger.log(Level.SEVERE, null, ex);
        MyMessages.error("SQL Error", "TvRage ID could not be saved in database");
      }
    }
    button_cancelActionPerformed(evt);
    //MySeries.glassPane.deactivate();
  }//GEN-LAST:event_button_okActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_ok;
  protected javax.swing.JComboBox combo_results;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel label_title;
  protected javax.swing.JProgressBar progress;
  // End of variables declaration//GEN-END:variables

  
}
