/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhotoPanel.java
 *
 * Created on 5 Σεπ 2010, 10:44:29 μμ
 */
package tools.feeds;

import com.sun.syndication.feed.synd.SyndEntryImpl;
import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import myComponents.myGUI.MyScrollableFlowPanel;
import tools.options.Options;

/**
 *
 * @author lordovol
 */
public class FeedPanel extends javax.swing.JPanel implements Runnable {

  public static final int FEED_WIDTH = 600;
  public static final int FEED_HEIGHT= 200;
  public static final long serialVersionUID = 235346345645L;
  public static final Color BORDER_HIGHLIGHT_COLOR = Color.BLACK;
  public static final Color BORDER_MEDIUM_COLOR = Color.LIGHT_GRAY;
  private MyScrollableFlowPanel feedPanel;
  private int index;
  private SyndEntryImpl entry;

  /** Creates new form PhotoPanel */
  public FeedPanel() {
    initComponents();
  }

  FeedPanel(MyScrollableFlowPanel feedPanel, SyndEntryImpl entry) {
    this.feedPanel = feedPanel;
    this.entry = entry;
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    label_title = new javax.swing.JLabel();
    label_date = new javax.swing.JLabel();
    scroll = new javax.swing.JScrollPane();
    ep_content = new javax.swing.JEditorPane();

    setBackground(new java.awt.Color(255, 255, 255));
    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    label_title.setBackground(new java.awt.Color(255, 255, 255));
    label_title.setFont(label_title.getFont().deriveFont(label_title.getFont().getStyle() | java.awt.Font.BOLD, label_title.getFont().getSize()+1));
    label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_title.setText("jLabel1");
    label_title.setOpaque(true);

    label_date.setFont(label_date.getFont().deriveFont((label_date.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, label_date.getFont().getSize()-1));
    label_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_date.setText("jLabel1");

    scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scroll.setViewportView(ep_content);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(label_date, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
          .addComponent(scroll, javax.swing.GroupLayout.Alignment.LEADING))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label_title)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label_date)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  public void selectFeed() {
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JEditorPane ep_content;
  private javax.swing.JLabel label_date;
  private javax.swing.JLabel label_title;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables

  public void run() {
    label_title.setText(entry.getTitle());
    DateFormat df = new SimpleDateFormat(Options.toString(Options.DATE_FORMAT));
    label_date.setText(df.format(entry.getPublishedDate()));
    ep_content.setContentType(entry.getDescription().getType());
    ep_content.setText(entry.getDescription().getValue());
    setPreferredSize(new Dimension(FEED_WIDTH,FEED_HEIGHT));
    setMaximumSize(new Dimension(FEED_WIDTH,FEED_HEIGHT));
    feedPanel.add(this);
    feedPanel.revalidate();
    feedPanel.repaint();

  }
}
