/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InternetUpdate.java
 *
 * Created on 8 Ιαν 2009, 9:26:04 μμ
 */
package tools.internetUpdate;

import tools.internetUpdate.epguides.EgUpdate;
import tools.internetUpdate.tvrage.TrUpdate;
import database.SeriesRecord;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import myComponents.MyMessages;
import myComponents.myGUI.MyDraggable;
import myseries.MySeries;
import tools.options.Options;

/**
 *
 * @author lordovol
 */
public class InternetUpdate extends MyDraggable {

  private MySeries m;
  private Thread t;
  private SeriesRecord currentSeries = null;
  private static final long serialVersionUID = 4364575758658L;
  public boolean finished = false;


  /** Creates new form InternetUpdate
   * @param m
   */
  public InternetUpdate(MySeries m) {
    this.m = m;
    initComponents();
    startUpdate();
    setLocationRelativeTo(m);
    setVisible(true);

  }

  public InternetUpdate(MySeries m, SeriesRecord currentSeries) {
    this.m = m;
    this.currentSeries = currentSeries;
    initComponents();
    startUpdate();
    setLocationRelativeTo(m);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    label_update_series = new javax.swing.JLabel();
    progress_bar = new javax.swing.JProgressBar();
    button_close = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    editor_messages = new javax.swing.JEditorPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("MySeries - Internet Update");

    progress_bar.setStringPainted(true);

    button_close.setText("Close");
    button_close.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_closeActionPerformed(evt);
      }
    });

    editor_messages.setContentType("text/html");
    jScrollPane1.setViewportView(editor_messages);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
          .addComponent(label_update_series, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
          .addComponent(progress_bar, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
          .addComponent(button_close))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(label_update_series, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        .addComponent(button_close)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void startUpdate() {
    Runnable task = null;
    if (Options.toString(Options.INTERNET_UPDATE_DB).equals(Options._EP_GUIDES_NAME_)) {
      task = new EgUpdate(this);
    } else if (Options.toString(Options.INTERNET_UPDATE_DB).equals(Options._TV_RAGE_NAME_)) {
      task = new TrUpdate(this);
    } else {
      return;
    }
    MySeries.logger.log(Level.INFO, "Starting update");
    t = new Thread(task);
    t.start();
  }

  private void button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_closeActionPerformed
    if (t == null) {
      MySeries.glassPane.deactivate();
      dispose();
    } else {

      if (finished) {
        MySeries.glassPane.deactivate();
        dispose();
      } else {
        int i = MyMessages.question("Abort?", "Do you want to cancel the update?");
        if (i == JOptionPane.OK_OPTION) {
          t.interrupt();
          MySeries.glassPane.deactivate();
          dispose();
        } else {
        }
      }
    }
}//GEN-LAST:event_button_closeActionPerformed

  /**
   * @return the currentSeries
   */
  public SeriesRecord getCurrentSeries() {
    return currentSeries;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button_close;
  javax.swing.JEditorPane editor_messages;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JLabel label_update_series;
  public javax.swing.JProgressBar progress_bar;
  // End of variables declaration//GEN-END:variables
}
