/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LatestNews.java
 *
 * Created on 26 Μαϊ 2011, 1:21:38 μμ
 */
package tools.misc.latestNews;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import myComponents.MyMessages;
import myComponents.MyUsefulFunctions;
import myComponents.myGUI.MyDraggable;
import myseries.MySeries;
import tools.MySeriesLogger;
import tools.options.Options;

/**
 *
 * @author Spyros Soldatos
 */
public class LatestNews extends MyDraggable {

  private static final long serialVersionUID = 1346346363L;
  private MySeries m;
  private boolean onStartUp;
  private boolean isConected;
  private String LATESTNEWS_URL = "http://code.google.com/p/myseriesproject/wiki/LatestNews?ts=1306404297&updated=LatestNews";
  private ReadNews readNews;

  public LatestNews(MySeries m, boolean onStartUp) {
    this.m = m;
    this.onStartUp = onStartUp;
    if (!onStartUp) {
      MySeries.glassPane.activate(null);
    }
    MySeriesLogger.logger.log(Level.INFO, "Initializing components");
    initComponents();
    MySeriesLogger.logger.log(Level.FINE, "Components initialized");
    if (check()) {
      readNews = new ReadNews();
      Thread t = new Thread(readNews);
      t.start();
    } else {
      MySeries.glassPane.deactivate();
      return;
    }
    if (!onStartUp) {
      setLocationRelativeTo(null);
      setVisible(true);
    }
  }

  class ReadNews implements Runnable {

    private int latestNewsViewed;

    @Override
    public void run() {
      try {
        MySeriesLogger.logger.log(Level.INFO, "Checking for updates");
        latestNewsViewed = Options.toInt(Options.LATEST_NEWS_ID);
        ArrayList<OnlineNew> news = getOnlineNews();
      } catch (MalformedURLException ex) {
        MySeriesLogger.logger.log(Level.SEVERE, "Could not connect to server", ex);
      } catch (IOException ex) {
        MySeriesLogger.logger.log(Level.SEVERE, "Could not read from server", ex);
      }


    }
  }

  private ArrayList<OnlineNew> getOnlineNews() throws MalformedURLException, IOException {
    ArrayList<OnlineNew> news = new ArrayList<OnlineNew>();
    MySeriesLogger.logger.log(Level.INFO, "Getting the latest version");
    URL v = new URL(LATESTNEWS_URL);
    BufferedReader in = new BufferedReader(new InputStreamReader(v.openStream()));
    label_status.setText("Reading news!!!");
    progress.setIndeterminate(true);
    progress.setString("");
    MySeriesLogger.logger.log(Level.FINE, "Latest version found");
    String inputLine;
    while ((inputLine = in.readLine()) != null) {
      int pos = inputLine.indexOf("<div title=\"news_");
      if (pos > -1) {
        OnlineNew n = new OnlineNew(inputLine);
        news.add(n);
      }
    }
    progress.setIndeterminate(false);
    progress.setString("");
    in.close();

    return news;
  }

  class OnlineNew {
    int id;
    String date;
    String title;
    String news;

    private OnlineNew(String inputLine) {
      String[] tokens = inputLine.split("<div title=\"news_");
      
      if(tokens.length >1){
        String[] t = tokens[1].split("(\">)|( : )|(<br></br>)");
        id = Integer.parseInt(t[0]);
        date = t[1];
        title = t[2];
        news = MyUsefulFunctions.stripHTML(t[3]);
      }
      System.out.println(this);
    }

    @Override
    public String toString() {
      return id +"."+date+" - " + title + " : " + news;
    }
    
  }

  private boolean check() {
    isConected = MyUsefulFunctions.hasInternetConnection(LATESTNEWS_URL);
    if (!isConected) {
      MyMessages.internetError(!onStartUp);
      return false;
    }
    return true;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    outer = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    bt_close = new myComponents.myGUI.buttons.MyButtonCancel();
    inner = new javax.swing.JPanel();
    label_status = new javax.swing.JLabel();
    progress = new javax.swing.JProgressBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    outer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("MySerieS Lates News");

    bt_close.setToolTipText("Close");
    bt_close.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bt_closeActionPerformed(evt);
      }
    });

    inner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    inner.setOpaque(false);

    label_status.setText(" ");

    javax.swing.GroupLayout innerLayout = new javax.swing.GroupLayout(inner);
    inner.setLayout(innerLayout);
    innerLayout.setHorizontalGroup(
      innerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(innerLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(innerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
          .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    innerLayout.setVerticalGroup(
      innerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(innerLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label_status)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(202, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout outerLayout = new javax.swing.GroupLayout(outer);
    outer.setLayout(outerLayout);
    outerLayout.setHorizontalGroup(
      outerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(outerLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(outerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outerLayout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(bt_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(outerLayout.createSequentialGroup()
            .addComponent(inner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())))
    );
    outerLayout.setVerticalGroup(
      outerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(outerLayout.createSequentialGroup()
        .addGroup(outerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(bt_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(outer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(outer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
    dispose();
    MySeries.glassPane.deactivate();
  }//GEN-LAST:event_bt_closeActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private myComponents.myGUI.buttons.MyButtonCancel bt_close;
  private javax.swing.JPanel inner;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel label_status;
  private javax.swing.JPanel outer;
  private javax.swing.JProgressBar progress;
  // End of variables declaration//GEN-END:variables
}
